name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run CI Script
        run: install
      - uses: actions/upload-artifact@v2
        with:
          name: .coverage.mypy-${{ matrix.platform }}_${{ matrix.python-version }}
          path: .coverage.mypy/
